/**
 * Tool-count drift guard.
 *
 * The ListTools handler returns `toolDescriptors` verbatim, so that array is
 * the single source of truth for "how many tools does this server expose".
 * Prose elsewhere (header doc-comments, the startup banner, the npm/README
 * description) has historically drifted away from it - e.g. headers said
 * "60 tools" long after the array reached 71, which is exactly what a
 * README-reading registry scanner (MCPpedia) keys on.
 *
 * This test locks the prose to the array:
 *   1. Every `@tool-count N` sentinel in the source must equal the array length.
 *   2. The startup banner must interpolate the array length, never a literal.
 *
 * To change the tool count: add/remove entries in src/tools.ts, then update the
 * `@tool-count` sentinels. This test fails the build until they agree.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { toolDescriptors } from "../src/tools.js";

const ROOT = process.cwd();
const read = (rel: string): string => readFileSync(join(ROOT, rel), "utf8");

// Files that carry a canonical, CI-enforced tool count.
const SENTINEL_FILES = ["src/tools.ts", "src/server.ts"];

describe("tool-count drift guard", () => {
  const actual = toolDescriptors.length;

  it("exposes the expected number of tools (71 at v0.8.0)", () => {
    // A literal floor/anchor so a silent mass-deletion of descriptors is caught
    // even if someone "helpfully" updated the sentinels to match.
    expect(actual).toBe(71);
  });

  it("every @tool-count sentinel equals toolDescriptors.length", () => {
    const found: Array<{ file: string; n: number }> = [];
    for (const file of SENTINEL_FILES) {
      const src = read(file);
      for (const m of src.matchAll(/@tool-count\s+(\d+)/g)) {
        found.push({ file, n: Number(m[1]) });
      }
    }

    // The guard is worthless if nothing is annotated - fail loudly if the
    // sentinels were removed.
    expect(found.length, "no @tool-count sentinels found in source").toBeGreaterThan(0);

    for (const { file, n } of found) {
      expect(
        n,
        `@tool-count in ${file} is ${n} but toolDescriptors.length is ${actual}`,
      ).toBe(actual);
    }
  });

  it("startup banner stays dynamic (never hardcodes the count)", () => {
    const server = read("src/server.ts");
    // Banner must interpolate the array length...
    expect(server).toMatch(
      /listening on stdio \(\$\{toolDescriptors\.length\} tools/,
    );
    // ...and must never hardcode a numeric count there.
    expect(server).not.toMatch(/listening on stdio \(\d+ tools/);
  });

  it("all tool names are unique (no accidental duplicate descriptors)", () => {
    const names = toolDescriptors.map((t) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  // The README tool catalog is the surface registry scanners (MCPpedia) read to
  // count tools. It is generated by scripts/gen-readme-tools.mjs; these two tests
  // keep it locked to the array and inside the scanner's 8 KB slice.
  it("README tool catalog lists every tool (count matches the array)", () => {
    const readme = read("README.md");
    const b = readme.indexOf("<!-- BEGIN TOOL CATALOG");
    const e = readme.indexOf("<!-- END TOOL CATALOG -->");
    expect(b, "tool catalog markers missing from README.md").toBeGreaterThanOrEqual(0);
    expect(e).toBeGreaterThan(b);

    const block = readme.slice(b, e);
    const rows = [...block.matchAll(/^- `([a-z0-9_]+)`/gm)].map((m) => m[1]);
    expect(
      rows.length,
      `README catalog has ${rows.length} rows but toolDescriptors.length is ${actual} — run \`npm run build && node scripts/gen-readme-tools.mjs --write --details\``,
    ).toBe(actual);

    const listed = new Set(rows);
    const missing = toolDescriptors.map((t) => t.name).filter((n) => !listed.has(n));
    expect(missing, `tools missing from README catalog: ${missing.join(", ")}`).toEqual([]);
  });

  it("README tool catalog stays within the 8000-char scanner window", () => {
    const readme = read("README.md");
    const END = "<!-- END TOOL CATALOG -->";
    const endOffset = readme.indexOf(END) + END.length;
    expect(
      endOffset,
      `catalog ends at char ${endOffset}; README-reading scanners slice only the first 8000`,
    ).toBeLessThanOrEqual(8000);
  });
});
